### ISSUE TITLE
Clean up build workflows

### ISSUE THREAD

**Issue by mbargull** [bioconda/bioconda-containers#64]
This repository was created some months before [reusable workflows became generally available](https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/) with the intention to use those later.
That hasn't happened yet, and as such, the workflows still have largely duplicate code.

**Comment by daler** [comment]
Now addressed in https://github.com/bioconda/bioconda-utils/pull/953 via a unified build script.
